from .common import (
    CONTRASTIVE_EVIDENCE_JUDGE_PROMPT,
    EPOCH_TRAJECTORY_COMPARISON_JUDGE_PROMPT,
    EPOCH_COVERAGE_REPAIR_PROMPT,
    EPOCH_EDIT_MERGE_PROMPT,
    EPOCH_EDIT_RANK_PROMPT,
    EVIDENCE_COVERAGE_AUDIT_PROMPT,
    LONGITUDINAL_MEMORY_PROMPT,
    SELECTION_FEEDBACK_EXTRACTOR_PROMPT,
    SKILL_MANAGER_L1_FAILURE_EVIDENCE_PROMPT,
    SKILL_MANAGER_L1_EVIDENCE_PROMPT,
    SKILL_MANAGER_L1_SUCCESS_EVIDENCE_PROMPT,
    SKILL_MANAGER_L2_MARKDOWN_PROMPT,
    SKILL_JUDGE_L1_EVIDENCE_PROMPT,
    SKILL_JUDGE_L2_MARKDOWN_PROMPT,
    SKILL_REFLECT_L2_MARKDOWN_PROMPT,
)
from .alfworld import (
    ALFWORLD_ACTION_AGENT_PROMPT,
    ALFWORLD_SKILL_JUDGE_L1_EVIDENCE_PROMPT,
    ALFWORLD_SKILL_JUDGE_L2_MARKDOWN_PROMPT,
    ALFWORLD_SKILL_REFLECT_L2_MARKDOWN_PROMPT,
    ALFWORLD_SKILL_MANAGER_L1_EVIDENCE_PROMPT,
    ALFWORLD_SKILL_MANAGER_L1_FAILURE_EVIDENCE_PROMPT,
    ALFWORLD_SKILL_MANAGER_L1_SUCCESS_EVIDENCE_PROMPT,
)
from .scienceworld import (
    SCIENCEWORLD_EPOCH_COVERAGE_REPAIR_PROMPT,
    SCIENCEWORLD_EPOCH_EDIT_MERGE_PROMPT,
    SCIENCEWORLD_EPOCH_EDIT_RANK_PROMPT,
    SCIENCEWORLD_EVIDENCE_COVERAGE_AUDIT_PROMPT,
    SCIENCEWORLD_LONGITUDINAL_MEMORY_PROMPT,
    SCIENCEWORLD_ACTION_AGENT_PROMPT,
    SCIENCEWORLD_SKILL_JUDGE_L1_EVIDENCE_PROMPT,
    SCIENCEWORLD_SKILL_JUDGE_L2_MARKDOWN_PROMPT,
    SCIENCEWORLD_SKILL_REFLECT_L2_MARKDOWN_PROMPT,
    SCIENCEWORLD_SKILL_MANAGER_L1_FAILURE_EVIDENCE_PROMPT,
    SCIENCEWORLD_SKILL_MANAGER_L1_EVIDENCE_PROMPT,
    SCIENCEWORLD_SKILL_MANAGER_L1_SUCCESS_EVIDENCE_PROMPT,
    SCIENCEWORLD_SKILL_MANAGER_L2_MARKDOWN_PROMPT,
)
from .appworld import (
    APPWORLD_ACTION_AGENT_PROMPT,
    APPWORLD_EPOCH_COVERAGE_REPAIR_PROMPT,
    APPWORLD_EPOCH_EDIT_MERGE_PROMPT,
    APPWORLD_EPOCH_EDIT_RANK_PROMPT,
    APPWORLD_EVIDENCE_COVERAGE_AUDIT_PROMPT,
    APPWORLD_SKILL_JUDGE_L1_EVIDENCE_PROMPT,
    APPWORLD_SKILL_JUDGE_L2_MARKDOWN_PROMPT,
    APPWORLD_SKILL_REFLECT_L2_MARKDOWN_PROMPT,
    APPWORLD_SKILL_MANAGER_L1_EVIDENCE_PROMPT,
    APPWORLD_SKILL_MANAGER_L1_FAILURE_EVIDENCE_PROMPT,
    APPWORLD_SKILL_MANAGER_L1_SUCCESS_EVIDENCE_PROMPT,
    APPWORLD_SKILL_MANAGER_L2_MARKDOWN_PROMPT,
)


def prompts_for_dataset(dataset):
    key = str(dataset or "alfworld").lower()
    common = {
        "skill_manager_l1": SKILL_MANAGER_L1_EVIDENCE_PROMPT,
        "skill_manager_l1_failure": SKILL_MANAGER_L1_FAILURE_EVIDENCE_PROMPT,
        "skill_manager_l1_success": SKILL_MANAGER_L1_SUCCESS_EVIDENCE_PROMPT,
        "skill_manager_l2": SKILL_MANAGER_L2_MARKDOWN_PROMPT,
        "skill_judge_l1": SKILL_JUDGE_L1_EVIDENCE_PROMPT,
        "skill_judge_l2": SKILL_JUDGE_L2_MARKDOWN_PROMPT,
        "skill_reflector_l2": SKILL_REFLECT_L2_MARKDOWN_PROMPT,
        "epoch_coverage_repair_merger": EPOCH_COVERAGE_REPAIR_PROMPT,
        "evidence_coverage_auditor": EVIDENCE_COVERAGE_AUDIT_PROMPT,
        "epoch_edit_merger": EPOCH_EDIT_MERGE_PROMPT,
        "epoch_edit_ranker": EPOCH_EDIT_RANK_PROMPT,
        "selection_feedback_extractor": SELECTION_FEEDBACK_EXTRACTOR_PROMPT,
        "longitudinal_memory": LONGITUDINAL_MEMORY_PROMPT,
        "contrastive_evidence_judge": CONTRASTIVE_EVIDENCE_JUDGE_PROMPT,
        "epoch_trajectory_comparison_judge": EPOCH_TRAJECTORY_COMPARISON_JUDGE_PROMPT,
    }
    if key == "alfworld":
        return {
            **common,
            "skill_manager_l1": ALFWORLD_SKILL_MANAGER_L1_EVIDENCE_PROMPT,
            "skill_manager_l1_failure": ALFWORLD_SKILL_MANAGER_L1_FAILURE_EVIDENCE_PROMPT,
            "skill_manager_l1_success": ALFWORLD_SKILL_MANAGER_L1_SUCCESS_EVIDENCE_PROMPT,
            "skill_judge_l1": ALFWORLD_SKILL_JUDGE_L1_EVIDENCE_PROMPT,
            "skill_judge_l2": ALFWORLD_SKILL_JUDGE_L2_MARKDOWN_PROMPT,
            "skill_reflector_l2": ALFWORLD_SKILL_REFLECT_L2_MARKDOWN_PROMPT,
            "action_agent": ALFWORLD_ACTION_AGENT_PROMPT,
        }
    if key in {"scienceworld", "science_world"}:
        return {
            **common,
            "skill_manager_l1": SCIENCEWORLD_SKILL_MANAGER_L1_EVIDENCE_PROMPT,
            "skill_manager_l1_failure": SCIENCEWORLD_SKILL_MANAGER_L1_FAILURE_EVIDENCE_PROMPT,
            "skill_manager_l1_success": SCIENCEWORLD_SKILL_MANAGER_L1_SUCCESS_EVIDENCE_PROMPT,
            "skill_manager_l2": SCIENCEWORLD_SKILL_MANAGER_L2_MARKDOWN_PROMPT,
            "skill_judge_l1": SCIENCEWORLD_SKILL_JUDGE_L1_EVIDENCE_PROMPT,
            "skill_judge_l2": SCIENCEWORLD_SKILL_JUDGE_L2_MARKDOWN_PROMPT,
            "skill_reflector_l2": SCIENCEWORLD_SKILL_REFLECT_L2_MARKDOWN_PROMPT,
            "action_agent": SCIENCEWORLD_ACTION_AGENT_PROMPT,
        }
    if key == "appworld":
        return {
            **common,
            "skill_manager_l1": APPWORLD_SKILL_MANAGER_L1_EVIDENCE_PROMPT,
            "skill_manager_l1_failure": APPWORLD_SKILL_MANAGER_L1_FAILURE_EVIDENCE_PROMPT,
            "skill_manager_l1_success": APPWORLD_SKILL_MANAGER_L1_SUCCESS_EVIDENCE_PROMPT,
            "skill_manager_l2": APPWORLD_SKILL_MANAGER_L2_MARKDOWN_PROMPT,
            "skill_judge_l1": APPWORLD_SKILL_JUDGE_L1_EVIDENCE_PROMPT,
            "skill_judge_l2": APPWORLD_SKILL_JUDGE_L2_MARKDOWN_PROMPT,
            "skill_reflector_l2": APPWORLD_SKILL_REFLECT_L2_MARKDOWN_PROMPT,
            "epoch_coverage_repair_merger": APPWORLD_EPOCH_COVERAGE_REPAIR_PROMPT,
            "evidence_coverage_auditor": APPWORLD_EVIDENCE_COVERAGE_AUDIT_PROMPT,
            "epoch_edit_merger": APPWORLD_EPOCH_EDIT_MERGE_PROMPT,
            "epoch_edit_ranker": APPWORLD_EPOCH_EDIT_RANK_PROMPT,
            "action_agent": APPWORLD_ACTION_AGENT_PROMPT,
        }
    raise ValueError(f"Unsupported dataset: {dataset!r}")
