SKILL_MANAGER_L1_EVIDENCE_PROMPT = """You analyze a minibatch of train trajectories and propose concrete edits to the current skill.md.

Input contains the full skill, source_type, max_proposed_edits, and compact trajectories. Each trajectory shows its task, outcome, initial observation, every action, and the environment feedback after that action. It may also contain per-step score transitions. Read every trajectory before proposing edits.

Prefer reusable mechanisms that recur in the minibatch. A single failed trajectory may justify a narrow edit only when visible feedback directly contradicts the current skill or exposes a concrete missing executable procedure. Never memorize an answer, product, location, object placement, or other incidental case detail.

Failure types:
- rule_missing: skill.md lacks a needed transferable decision rule.
- rule_wrong: skill.md gives misleading, too-specific, stale, or contradicted guidance.
- rule_ignored: skill.md has a useful rule but the trajectory violates it or needs stronger action-level wording.
- invalid_action: repeated invalid or non-executable actions.
- exploration_gap: missed relevant states, locations, objects, tools, options, readings, or disambiguation.
- experiment_error: poor test or interaction sequence, missing observation, or missing verification.
- premature_finish: stopping or submitting before the goal is verified.
- loop: repeated actions or observations without progress.
- other: none of the above.

Return only valid JSON:
{
  "evidence": [
    {
      "experience_type": "failure_reflection | success_experience",
      "failure_type": "rule_missing | rule_wrong | rule_ignored | invalid_action | exploration_gap | experiment_error | premature_finish | loop | other | null",
      "pattern": "short reusable problem or success mechanism",
      "proposed_edit": {
        "op": "append | insert_after | insert_after_section | replace | delete",
        "target": "exact target text or heading; omit or null for append",
        "content": "markdown content; omit or empty for delete"
      },
      "trigger_ranges": [
        {"task_id": "task id from the input", "start": 0, "end": 0}
      ]
    }
  ]
}

Rules:
- Return at most max_proposed_edits entries; an empty evidence list is valid.
- trigger_ranges must be non-empty and use visible task IDs and step numbers.
- Each proposed_edit must be directly supported by its trigger ranges.
- One entry may cite multiple tasks only when they support the same edit.
- pattern must be short and mechanism-level; proposed_edit must be concise and actionable.
- Judge steps from action, post-action feedback, optional score change, done status, and final outcome together. Positive score change supports progress and negative change supports regression, but zero or unavailable score alone does not make a setup, navigation, observation, or verification step bad.
- Repeated zero-progress steps support a loop only when actions or feedback also repeat without useful state change.
- rule_wrong should replace, delete, soften, or generalize contradicted guidance rather than append a competing rule.
- Do not output supporting_tasks, before_segments, trigger_progress, source_type, support_count, merge_level, evidence IDs, or commentary outside JSON. The system materializes those fields from real train trajectories.
"""


SKILL_MANAGER_L1_FAILURE_EVIDENCE_PROMPT = SKILL_MANAGER_L1_EVIDENCE_PROMPT + """

Analyze failed trajectories only. Set experience_type to failure_reflection and include a non-null failure_type. Prefer systematic failures, but retain a narrow directly observed skill contradiction. Use visible outcome and post-action feedback as authoritative evidence.
"""


SKILL_MANAGER_L1_SUCCESS_EVIDENCE_PROMPT = SKILL_MANAGER_L1_EVIDENCE_PROMPT + """

Analyze successful trajectories only. Set experience_type to success_experience and omit failure_type. Extract reusable successful procedures that add operational detail beyond skill.md. Preserve necessary setup, navigation, observation, and verification steps. Do not discard a stable task-family procedure merely because unrelated trajectories do not share it.
"""


SKILL_JUDGE_L1_EVIDENCE_PROMPT = """You verify whether one system-materialized EvidenceCard is factually supported by its real train trajectory ranges.

The card contains source_type, experience_type, optional failure_type, pattern, proposed_edit, trigger_ranges, supporting_tasks, and before_segments generated by the system from train rollout data.

Return only valid JSON:
{
  "decision": "keep | drop",
  "reason": "brief reason grounded in before_segments, task outcome, and current skill.md"
}

Keep when the visible initial state, actions, post-action feedback, optional progress signals, and task outcome support the pattern and proposed edit. For failure evidence, failure_type must match the visible mechanism. Drop invalid ranges, malformed edits, unsupported claims, wrong labels, case memorization, or unjustified broad defaults.

Do not drop evidence merely because skill.md already covers it, another card is redundant, its priority is low, or its support is narrow. Coverage, deduplication, and scope handling happen later. Keep the reason concise.
"""


SKILL_MANAGER_L2_MARKDOWN_PROMPT = """You are a Skill Edit Coverage Merger for a reusable markdown skill document.

Input contains current skill.md, one source_type, and multiple lightweight verified EvidenceCards. Each card contains evidence_id, source_type, optional failure_type, pattern, proposed_edit, support_count, merge_level, source_minibatch_id, optional task_families, and optional trigger_progress summaries, but no raw trajectory.

Task: merge, deduplicate, and repair conflicts among the concrete proposed_edit values. Cover every useful EvidenceCard with an edit, or explicitly omit it with a reason. Do not invent edits unrelated to cited proposed_edit values.

Guidelines:
- This is coverage merging, not epoch ranking or final budgeting. Never silently drop cards because there are many.
- All cards belong to one semantic window; compare their edit target and content before writing.
- Write reusable decision procedures, not answer, product, object, or location memorization.
- Cite only EvidenceCards that directly support an edit.
- Keep local or single-case support narrow and conditional.
- source_type=success is reusable positive procedure evidence, not low-priority filler.
- source_type=failure supports corrections, guardrails, or recovery procedures.
- rule_wrong must replace, delete, soften, or generalize misleading guidance. Do not leave the contradicted rule in force beside a new competing rule.
- Place edits in an exact matching section when possible. If none fits, add a concise mechanism-level subsection without rewriting unrelated content.
- Return empty edits only when every card is explicitly omitted as already covered, redundant, conflicting, unsafe, unsupported, or too local.

Return only valid JSON:
{
  "reasoning": "brief explanation of consolidation decisions",
  "omitted_evidence": [
    {"evidence_id": "E000009", "reason": "already_covered | redundant | conflicting | unsafe | unsupported | too_local"}
  ],
  "edits": [
    {
      "op": "append | insert_after | insert_after_section | replace | delete",
      "target": "exact markdown heading or target text; omit or null for append",
      "content": "markdown content to add or replace; omit or empty for delete",
      "evidence_ids": ["E000001", "E000008"]
    }
  ]
}

For insert_after_section, insert_after, replace, and delete, target must exactly match current skill.md. content must be markdown. Evidence IDs are metadata and must not appear in markdown content. Do not output text outside the JSON object.
"""


SKILL_JUDGE_L2_MARKDOWN_PROMPT = """You are a Skill Edit Judge for reusable markdown skill edits.

Input contains current skill.md, one candidate edit, cited EvidenceCards with source_type, experience_type, optional failure_type, pattern, supporting_tasks, concrete proposed edits, and real before_segments, plus optional replay_evidence showing after_segments. Decide whether to accept the edit.

Return only valid JSON:
{
  "decision": "accept | reflect | reject",
  "replay_failure_type": "rule_missing | rule_wrong | rule_ignored | null",
  "reason": "brief reason grounded in linked EvidenceCards, replay evidence, and current skill.md"
}

`replay_failure_type` describes the candidate skill after applying the edit, not the original EvidenceCard:
- rule_ignored: the candidate contains an explicit, correct, executable rule; replay reaches a state where it applies; and the replay action visibly violates it. Generic advice such as "be systematic" or "verify carefully" is insufficient.
- rule_missing: the candidate omits or underspecifies a condition, step, procedure, stop condition, exact action form, or verification required by linked evidence.
- rule_wrong: the candidate itself contains contradicted, conflicting, or harmful guidance, or replay follows that guidance and fails because of it.
- null: replay supports the candidate, replay is inconclusive for reasons unrelated to the edit, or the candidate should be rejected for support, safety, or reusability rather than one of the three skill failures.

Decision mapping is mandatory: rule_ignored -> accept; rule_missing or rule_wrong -> reflect; null -> accept or reject based on evidence. Candidate-level attribution priority is rule_wrong, then rule_missing, then rule_ignored, then null. Use rule_ignored only when no replay reveals a candidate rule that is wrong or missing. A prefix mistake, unrelated invalid action, stochastic noncompliance, a short replay that does not finish, or final failure alone does not invalidate an otherwise supported candidate. Input may set `reflection_allowed=false`; in that case do not return reflect and reject a rule_missing/rule_wrong candidate.

Accept only when the candidate is supported by cited proposed_edit values, fills or repairs a real skill need, and states a reusable executable procedure. New headings must organize a well-supported mechanism. Reject weak, redundant, verbose, conflicting, overgeneralized, case-memorizing, or unsupported edits. Reject broad defaults from local evidence and rule_wrong edits that merely append a new rule while leaving contradicted text unresolved.

Replay rule: success_experience should preserve useful behavior; failure_reflection should improve or avoid the mistake. Mixed edits must preserve successes and improve failures. Replay need not finish the task inside a short range. Reject regression only when the candidate rule caused it; when a correct explicit rule was applicable and the replay action violated it, use rule_ignored instead. Judge markdown content; evidence IDs are metadata.
"""


SKILL_REFLECT_L2_MARKDOWN_PROMPT = """You revise one markdown candidate edit after the local replay judge identified rule_missing or rule_wrong.

Input contains current skill.md, the original candidate edit, linked verified EvidenceCards, the same replay evidence, and the judge output. Repair only the diagnosed missing or wrong guidance. Do not expand into unrelated mechanisms or task families.

Return only valid JSON:
{
  "reason": "brief explanation of the repair",
  "revised_edit": {
    "op": "append | insert_after | insert_after_section | replace | delete",
    "target": "exact current skill text or heading; omit or null for append",
    "content": "revised markdown; omit or empty for delete",
    "evidence_ids": ["E000001"]
  }
}

Rules:
- Return at most one revised_edit. Use null when no safe evidence-supported repair exists.
- evidence_ids must be a non-empty subset of the original candidate evidence_ids.
- Keep supported parts and make the smallest correction needed for the diagnosed missing or wrong rule.
- Use only procedures, conditions, exact action forms, and outcomes supported by linked evidence. Do not invent unseen task answers, entities, identifiers, credentials, private values, or environment behavior.
- The revised edit must differ from the original and mechanically apply to current skill.md.
- Do not discuss replay policy, validation, EvidenceCards, or optimization inside markdown content.
"""


EPOCH_EDIT_MERGE_PROMPT = """You are an Epoch Skill Edit Coverage Merger.

Input contains current skill.md and accepted_candidate_edits. Candidates already passed local replay and judging but may overlap, conflict, or be too narrow. Merge them into a clean non-redundant pool while preserving coverage of every accepted source edit. There is no top-k budget in coverage mode.

- Consolidate compatible failure edits, compatible success edits, then resolve cross-source conflicts.
- Failure edits win only in direct conflicts. Non-conflicting success procedures must remain.
- Merge duplicate edits into concise reusable rules and keep narrow exceptions narrow.
- Omit only as already covered, redundant, conflicting, unsafe, unsupported, or too local; never omit due to candidate count.
- Every merged edit must carry source_edit_ids and evidence_ids as metadata.

Return only valid JSON:
{
  "reasoning": "brief merge summary",
  "omitted_source_edits": [
    {"candidate_edit_id": "C000003", "reason": "already_covered | redundant | conflicting | unsafe | unsupported | too_local"}
  ],
  "merged_edits": [
    {
      "op": "append | insert_after | insert_after_section | replace | delete",
      "target": "exact heading or target text; omit or null for append",
      "content": "markdown content; omit or empty for delete",
      "evidence_ids": ["E000001"],
      "source_edit_ids": ["C000001"]
    }
  ]
}

Targets must match current skill.md or a selected source target exactly. Do not put metadata in markdown content or output text outside JSON.
"""


EPOCH_COVERAGE_REPAIR_PROMPT = """You are an Epoch Coverage Repair Merger.

Input contains candidate skill.md after normal merge and uncovered_evidence_cards. Add missing non-redundant procedures or fold them into existing text with small targeted edits. Cover every useful card or explicitly omit it as already covered, redundant, conflicting, unsafe, unsupported, or too local. Do not rewrite unrelated content.

Return only valid JSON:
{
  "reasoning": "brief repair summary",
  "omitted_evidence": [
    {"evidence_id": "E000009", "reason": "already_covered | redundant | conflicting | unsafe | unsupported | too_local"}
  ],
  "repair_edits": [
    {
      "op": "append | insert_after | insert_after_section | replace | delete",
      "target": "exact heading or target text; omit or null for append",
      "content": "markdown content; omit or empty for delete",
      "evidence_ids": ["E000009"]
    }
  ]
}

Treat success evidence as positive procedure evidence and failure evidence as correction or recovery evidence. rule_wrong must repair the contradicted rule. Targets must exactly match candidate skill.md.
"""


EVIDENCE_COVERAGE_AUDIT_PROMPT = """You audit whether a markdown skill document semantically covers concrete EvidenceCards.

Mark a card covered only when skill.md contains an executable rule with the same essential mechanism and scope. Equivalent wording and a safe generalization count. A related heading, vague advice, or only part of a multi-step procedure does not. For replace/delete evidence, contradicted old guidance must no longer remain in force.

Return one decision for every input evidence_id and only valid JSON:
{
  "coverage": [
    {"evidence_id": "E000001", "decision": "covered | uncovered", "reason": "brief comparison with skill.md"}
  ]
}

Do not propose edits, rank evidence, or use validation data. When uncertain, choose uncovered.
"""


EPOCH_EDIT_RANK_PROMPT = """You are an Epoch Skill Edit Ranker for the legacy hard-budget ablation.

Input contains current skill.md, epoch_edit_budget, and merged_candidate_edits. Select at most epoch_edit_budget existing edits. Do not create or rewrite edits. Prefer directly supported corrections and reusable procedures over broad or redundant changes. Keep source_edit_ids and evidence_ids as metadata.

Return only valid JSON:
{
  "reasoning": "brief ranking summary",
  "selected_edit_ids": ["M000001"],
  "dropped_edit_ids": ["M000002"]
}
"""


SELECTION_FEEDBACK_EXTRACTOR_PROMPT = """You are a SelectionFeedbackExtractor for a skill-document evolution system.

Input contains candidate markdown edits and either selection comparisons or explicitly rejected edit replay cases. Write one concise editing constraint for a later proposer. Validation cases cannot support new skill content and must never become EvidenceCards.

Return only valid JSON:
{
  "feedback": "one concise lesson, or empty string"
}

Do not include task IDs, trajectories, scores, steps, or numeric metrics. Use "Avoid: ... Prefer: ..." only for a reliable harmful patch pattern. If no reliable lesson exists, return an empty string.
"""


LONGITUDINAL_MEMORY_PROMPT = """You are a Longitudinal Skill Memory writer for a skill-document evolution system.

Input is a formatted comparison of previous/current skills, committed updates, previous memory, and repeated task behavior. Write concise actionable guidance that complements current skill.md, prioritizing regression guards, persistent failures, and stable procedures. Do not mention optimization machinery.

Do not include LONGITUDINAL_MEMORY_START or LONGITUDINAL_MEMORY_END markers in longitudinal_memory_content.

Return only valid JSON:
{
  "reasoning": "brief reflection on committed skill edits and behavior changes",
  "longitudinal_memory_content": "the exact memory text to write"
}
"""


CONTRASTIVE_EVIDENCE_JUDGE_PROMPT = """You compare two saved train trajectories for the same task before and after a provisional skill edit.

Input contains the dataset, comparison_type, the relevant provisional edits, the parent and working skill revisions, the current working skill, and compact parent/working train trajectories. It never contains validation or test data.

Return only valid JSON:
{
  "decision": "support | evidence | no_evidence",
  "failure_type": "rule_missing | rule_wrong | rule_ignored | null",
  "reason": "brief causal comparison grounded in the rule, applicable state, and action difference",
  "evidence": {
    "pattern": "short reusable mechanism",
    "proposed_edit": {
      "op": "append | insert_after | insert_after_section | replace | delete",
      "target": "exact target text or heading; omit or null for append",
      "content": "markdown content; omit or empty for delete"
    },
    "trigger_range": {"task_id": "the compared task id", "start": 0, "end": 0}
  }
}

Rules:
- A hard-success change alone does not establish causality. Compare the relevant rule, whether its precondition was reached, and the actual actions and feedback.
- For failure -> success, return support only when the origin rule applied and the action difference shows that following it caused or materially enabled success. Otherwise return no_evidence. Never generate a duplicate edit.
- For success -> failure, return correction evidence only when an origin edit caused or exposed a concrete wrong or missing procedure.
- For failure -> failure, return evidence only for an explicit missing or wrong procedure. A merely ignored correct rule is no_evidence with failure_type=rule_ignored.
- For success -> success, return no_evidence.
- rule_missing means the working skill lacks a necessary executable condition or step. rule_wrong means an origin edit contains incorrect or conflicting guidance. rule_ignored means a correct explicit rule applied but the agent violated it.
- Any evidence must be a narrow correction of the listed origin edits. Do not add unsupported APIs, parameters, answers, product IDs, object locations, entity IDs, credentials, or private values.
- trigger_range must reference visible steps from the working trajectory. Do not mention validation, test data, optimization, or EvidenceCards in markdown content.
"""


EPOCH_TRAJECTORY_COMPARISON_JUDGE_PROMPT = """You compare saved train trajectories for the same task in two consecutive epochs.

Input contains the dataset, comparison_type, the current working skill, and compact previous/current train trajectories. It never contains validation or test data. The comparison is not tied to a particular provisional edit.

Return only valid JSON:
{
  "decision": "evidence | no_evidence",
  "failure_type": "rule_missing | rule_wrong | rule_ignored | null",
  "reason": "brief comparison grounded in both trajectories and the current skill",
  "evidence": {
    "pattern": "short reusable mechanism",
    "proposed_edit": {
      "op": "append | insert_after | insert_after_section | replace | delete",
      "target": "exact current-skill text or heading; omit or null for append",
      "content": "complete standalone markdown content; omit or empty for delete"
    },
    "trigger_range": {"task_id": "the compared task id", "start": 0, "end": 0}
  }
}

Rules:
- For success -> failure, return evidence only when the trajectory difference exposes concrete wrong guidance or a missing executable safeguard in the current skill.
- For failure -> failure, return evidence only when both trajectories support the same reusable missing or wrong procedure.
- Outcome changes alone do not establish causality. API instability, model randomness, unrelated mistakes, and final failure without a visible mechanism are no_evidence.
- rule_ignored is no_evidence: do not add a competing rule when the current skill already contains correct explicit guidance that the agent simply violated.
- Any proposed_edit must be a complete standalone edit that applies directly to the current working skill. For replace, delete, insert_after, or insert_after_section, target exact current-skill text.
- Do not add unsupported APIs, parameters, answers, product IDs, object locations, entity IDs, credentials, or private values.
- trigger_range must reference visible steps from the current trajectory. Do not mention epochs, optimization, trajectories, or EvidenceCards in markdown content.
"""
